# Generated by Django 3.1.4 on 2021-07-04 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='Student')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('roll', models.BigIntegerField()),
                ('birth_certificate', models.BigIntegerField(unique=True)),
                ('birthDate', models.DateField(null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('father_NID', models.BigIntegerField()),
                ('mother_NID', models.BigIntegerField()),
                ('contract', models.BigIntegerField()),
                ('present_Address', models.CharField(max_length=250)),
                ('permanent_Address', models.CharField(max_length=250)),
                ('Join_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_information.class')),
                ('candidate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_information.candidate')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_information.department')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_information.subject')),
                ('year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_information.yearofstudent')),
            ],
            options={
                'verbose_name_plural': 'Student List',
            },
        ),
    ]
