# Generated by Django 3.1.4 on 2021-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth_certificate',
            field=models.IntegerField(max_length=17),
        ),
        migrations.AlterField(
            model_name='students',
            name='contract',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_NID',
            field=models.IntegerField(max_length=14),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_NID',
            field=models.IntegerField(max_length=14),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.PositiveSmallIntegerField(max_length=20),
        ),
    ]
