# Generated by Django 3.1.4 on 2021-02-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210213_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth_certificate',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='contract',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_NID',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_NID',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.PositiveIntegerField(),
        ),
    ]
