# Generated by Django 3.1.4 on 2021-02-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20210222_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='birth_certificate',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='contract',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='father_NID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='mother_NID',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll',
            field=models.BigIntegerField(),
        ),
    ]
