# Generated by Django 3.1.4 on 2021-03-05 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_information', '0003_auto_20210222_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField()),
                ('pdf', models.FileField(blank=True, upload_to='Notic_Board/pdf')),
                ('image', models.ImageField(blank=True, upload_to='Notic_Board')),
                ('added_date', models.DateField(auto_now_add=True)),
                ('edited_date', models.DateField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
