# Generated by Django 3.1.4 on 2021-03-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_information', '0004_noticboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticboard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
