# Generated by Django 3.1.4 on 2021-03-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_information', '0005_noticboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticboard',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
