# Generated by Django 3.1.4 on 2021-03-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_information', '0006_auto_20210307_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticboard',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticboard',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
