# Generated by Django 3.1.4 on 2021-02-13 04:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('profile_pic', models.ImageField(blank=True, upload_to='HeadMaster_Manager')),
                ('bio', models.TextField(blank=True, max_length=400)),
                ('birth_date', models.DateField()),
                ('birth_Certificate', models.CharField(max_length=17)),
                ('NID', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=11)),
                ('Social_ID', models.URLField(blank=True)),
                ('Present_Address', models.CharField(max_length=200)),
                ('Permanent_Address', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Info',
            },
        ),
    ]
