# Generated by Django 3.1.4 on 2021-02-13 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearofstudent',
            name='year',
            field=models.PositiveSmallIntegerField(max_length=15),
        ),
    ]
